services:
  db:
    env_file: .env
    restart: always
    image: timescale/timescaledb:latest-pg14
    ports:
      - 127.0.0.1:${DB_PORT:?err}:5432
    volumes:
      - data:/var/lib/postgresql/data
  vault-watcher:
    env_file: .env
    restart: always
    build: .
  grafana:
    restart: always
    build:
      dockerfile: dash-templates/Dockerfile
      context: .
    env_file: .env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  data:
